# Generated by Django 4.2.10 on 2024-04-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
